spring:
    application:
        name: api-gateway
    main:
        web-application-type: reactive
    cloud:
        gateway:
            routes:
                - id: auth-service
                  uri: lb://auth-service
                  predicates:
                    - Path=/auth/**
                - id: quiz-service
                  uri: lb://quiz-service
                  predicates:
                    - Path=/quizzes/**
                  filters:
                    - AuthFilter
                - id : class-service
                  uri: lb://class-service
                  predicates:
                    - Path=/classes/**
                  filters:
                    - AuthFilter
                - id : file-service
                  uri: lb://file-service
                  predicates:
                    - Path=/files/**
                  filters:
                    - AuthFilter
        


server:
    port: 8080
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka
        register-with-eureka: true  
        fetch-registry: true
        
    instance:
        preferIpAddress: true